echo "30 ejecuciones de vs"
./vertexscan.sh
./vertexscan.sh
./vertexscan.sh
./vertexscan.sh
./vertexscan.sh
./vertexscan.sh
./vertexscan.sh
./vertexscan.sh
./vertexscan.sh
./vertexscan.sh
./vertexscan.sh
./vertexscan.sh
./vertexscan.sh
./vertexscan.sh
./vertexscan.sh
./vertexscan.sh
./vertexscan.sh
./vertexscan.sh
./vertexscan.sh
./vertexscan.sh
./vertexscan.sh
./vertexscan.sh
./vertexscan.sh
./vertexscan.sh
./vertexscan.sh
./vertexscan.sh
./vertexscan.sh
./vertexscan.sh
./vertexscan.sh
