./runHeurRPP.sh v Instancias_RPP/URPP/UR532
./runHeurRPP.sh v Instancias_RPP/URPP/UR147
./runHeurRPP.sh v Instancias_RPP/URPP/UR762
./runHeurRPP.sh v Instancias_RPP/URPP/UR742
./runHeurRPP.sh v Instancias_RPP/URPP/UR767
./runHeurRPP.sh v Instancias_RPP/URPP/PALMA
./runHeurRPP.sh v Instancias_RPP/URPP/UR765
./runHeurRPP.sh v Instancias_RPP/URPP/UR152
./runHeurRPP.sh v Instancias_RPP/URPP/UR565
./runHeurRPP.sh v Instancias_RPP/URPP/UR752
./runHeurRPP.sh v Instancias_RPP/URPP/UR735
./runHeurRPP.sh v Instancias_RPP/URPP/UR545
./runHeurRPP.sh v Instancias_RPP/URPP/UR552
./runHeurRPP.sh v Instancias_RPP/URPP/UR737
./runHeurRPP.sh v Instancias_RPP/URPP/UR555
./runHeurRPP.sh v Instancias_RPP/URPP/UR145
./runHeurRPP.sh v Instancias_RPP/URPP/UR757
./runHeurRPP.sh v Instancias_RPP/URPP/UR537
./runHeurRPP.sh v Instancias_RPP/URPP/UR157
./runHeurRPP.sh v Instancias_RPP/URPP/UR547
./runHeurRPP.sh v Instancias_RPP/URPP/UR745
./runHeurRPP.sh v Instancias_RPP/URPP/UR747
./runHeurRPP.sh v Instancias_RPP/URPP/UR155
./runHeurRPP.sh v Instancias_RPP/URPP/UR755
./runHeurRPP.sh v Instancias_RPP/URPP/UR732
./runHeurRPP.sh v Instancias_RPP/URPP/UR562
./runHeurRPP.sh v Instancias_RPP/URPP/UR142
./runHeurRPP.sh v Instancias_RPP/URPP/UR542
./runHeurRPP.sh v Instancias_RPP/URPP/UR557
./runHeurRPP.sh v Instancias_RPP/URPP/UR135
./runHeurRPP.sh v Instancias_RPP/URPP/UR132
./runHeurRPP.sh v Instancias_RPP/URPP/UR162
./runHeurRPP.sh v Instancias_RPP/URPP/UR167
./runHeurRPP.sh v Instancias_RPP/URPP/UR567
./runHeurRPP.sh v Instancias_RPP/URPP/UR535
./runHeurRPP.sh v Instancias_RPP/URPP/UR137
./runHeurRPP.sh v Instancias_RPP/URPP/UR165
